on:
  push:
  pull_request_target:
    branches: [master]
name: Tests / test-user-mirror (cached)
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Get Time
      id: get-time
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d%H%M%S")"
      shell: bash

    - name: Cache src repos
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: ${{ runner.os }}-hub-repos-cache-${{ steps.get-time.outputs.date }}
        restore-keys: ${{ runner.os }}-hub-repos-cache

    - name: Mirror Github to GitCode with white list and cache
      uses: ./.
      with:
        src: github/hu-qi
        dst: gitcode/huqi
        dst_key: ${{ secrets.GITCODE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITCODE_TOKEN }}
        cache_path: /github/workspace/hub-mirror-cache
        white_list: 'wcfjs_demo'
        force_update: true

    - name: Print cache path
      run: |
        ls -la ${{ github.workspace }}/hub-mirror-cache
